[advisories]
ignore = [
    "RUSTSEC-2020-0071", # chrono
    "RUSTSEC-2021-0145", # atty
    "RUSTSEC-2023-0071", # rsa: Marvin Attack: potential key recovery
] # advisory IDs to ignore e.g. ["RUSTSEC-2019-0001", ...]
